### ISSUE TITLE
Support arm64 and arm docker images

### ISSUE THREAD

**Issue by brlbil** [metal-stack/csi-lvm#44]
Thanks for this project, it is great. I would like to run this on some IoT devices.
Can you please also provide docker images for arm64 and arm

**Comment by majst01** [comment]
do you mind sending a pull request to add arm/arm64 support ?

**Comment by brlbil** [comment]
I did not see the comment `This driver is replaced by csi-driver-lvm, all further development happens there`
so should I work on sending a pull request to `csi-driver-lvm` project?

**Comment by majst01** [comment]
Yes, we should probably make this hint more prominent.

**Comment by brlbil** [comment]
So closing this one, thanks.
